### ISSUE TITLE
Help with construction (Lemfo T)

### ISSUE THREAD

**Issue by ghost** [OpenWatchProject/manifest#3]
I followed the instructions that can be found in the manifest file. After doing all these steps I get this message
 

python3 vendor/mediatek/proprietary/scripts/releasetools/split_build_helper.py full_c7s-userdebug
source build/envsetup.sh && export OUT_DIR=out_sys && lunch sys_mssi_64_cn-userdebug && make sys_images
source build/envsetup.sh && export OUT_DIR=out && lunch vnd_c7s-userdebug && make vnd_images krn_images
python out_sys/target/product/mssi_64_cn/images/split_build.py --system-dir out_sys/target/product/mssi_64_cn/images --vendor-dir out/target/product/c7s/images --kernel-dir out/target/product/c7s/images --output-dir out/target/product/c7s/merged

I do not know what to do next.  I'm trying youtube tutorials but I don't really know how to go about it in this case.  I am very much asking for guidance.

**Comment by iscle** [comment]
Hi, did the build finish successfully? If it did, then you will have the output files for SP Flash Tools in the out/target/product/c7s/merged folder.

**Comment by ghost** [comment]
![Screenshot from 2022-07-30 08-36-54](https://user-images.githubusercontent.com/100865716/181878107-2e71f617-d9ba-44ac-9833-83fdaf559ae0.png)

I am stuck at this very moment. I don't know too much what to do.

**Comment by ghost** [comment]
?

**Comment by iscle** [comment]
You need to execute each of the three commands that were printed by the script.

**Comment by ghost** [comment]
source build/envsetup.sh && export OUT_DIR=out_sys && lunch sys_mssi_64_cn-userdebug && make sys_images
![2](https://user-images.githubusercontent.com/100865716/182144222-a9bab412-21ef-436f-8925-75aa6d4e47c2.png)

source build/envsetup.sh && export OUT_DIR=out && lunch vnd_c7s-userdebug && make vnd_images krn_images
![Screenshot from 2022-08-01 14-08-18](https://user-images.githubusercontent.com/100865716/182144502-ebd88582-601a-4ea8-8afd-d716d24a8ed0.png)

python out_sys/target/product/mssi_64_cn/images/split_build.py --system-dir out_sys/target/product/mssi_64_cn/images --vendor-dir out/target/product/c7s/images --kernel-dir out/target/product/c7s/images --output-dir out/target/product/c7s/merged
![Screenshot from 2022-08-01 14-09-32](https://user-images.githubusercontent.com/100865716/182144654-e397c0b5-85fb-4be5-9d7f-07c9590bf575.png)

**Comment by ghost** [comment]
?

**Comment by ghost** [comment]
> You need to execute each of the three commands that were printed by the script.

Above I sent pictures with errors. What should I do next?

**Comment by ghost** [comment]
?
